/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_is_mi_illegal_image_ni_TargetClassifyJNI */

#ifndef _Included_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
#define _Included_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    initModel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIFFF)V
 */
JNIEXPORT void JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_initModel
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    extractOutputOfLayer
 * Signature: ([BLjava/lang/String;I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_extractOutputOfLayer
  (JNIEnv *, jclass, jbyteArray, jstring, jint);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    forwardNet
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_forwardNet
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    getBlobOutputByName
 * Signature: (Ljava/lang/String;I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_getBlobOutputByName
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    targetCheck
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_targetCheck
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    initDetector
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_initDetector
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    detectAndVerifyFace
 * Signature: ([BI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_detectAndVerifyFace
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_netease_is_mi_illegal_image_ni_TargetClassifyJNI
 * Method:    verifyFace
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_netease_is_mi_illegal_image_ni_TargetClassifyJNI_verifyFace
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
